export const themeEmojis: { [key: string]: string } = {
  // Seasonal Themes
  Halloween: '🎃',
  Winter: '❄️',
  Spring: '🌸',
  General: '⭐',
  
  // Subject Themes
  Math: '🔢',
  Reading: '📖',
  Science: '🔬',
  History: '🏛️',
  Geography: '🌍',
  Art: '🎨',
  Music: '🎵',
  'Physical Education': '⚽',
  Technology: '💻',
  'Social Studies': '🌐',
  'Language Arts': '✍️',
  'Foreign Language': '🗣️',
  'Special Education': '🌟',
  'Test Prep': '📝',
  'Study Skills': '📚',
  'Life Skills': '🌱',
  'Career Education': '💼',
  'Character Education': '❤️',
  'Health Education': '🏥',
  'Environmental Science': '🌿',
  'Computer Science': '🖥️',
  'Financial Literacy': '💰',
  'Critical Thinking': '🤔',
  'Creative Writing': '✏️',
  'Public Speaking': '🎤',
  'Research Skills': '🔍',
  'Problem Solving': '🧩',
  'Time Management': '⏰',
  'Organization Skills': '📊',
  'Leadership Skills': '👥',
  'Communication Skills': '💭',
  'Team Building': '🤝',
  'Conflict Resolution': '🤲',
  'Decision Making': '⚖️',
  'Goal Setting': '🎯',
  'Stress Management': '🧘',
  'Digital Citizenship': '🌐',
  'Media Literacy': '📱',
  'Information Literacy': '📰',
  'Cultural Awareness': '🌏',
  'Global Education': '🗺️',
  'Environmental Education': '🌳',
  'Character Development': '🌟',
  'Social Skills': '👥',
  'Emotional Intelligence': '❤️',
  'Growth Mindset': '🌱',
  'Mindfulness': '🧘',
  'Positive Behavior': '👍',
  'Self-Awareness': '🤗',
  'Self-Management': '⚡',
  'Responsible Decision-Making': '🎯',
  'Relationship Skills': '🤝',
  'Social Awareness': '👀',
  'College Readiness': '🎓',
  'Career Readiness': '💼',
  'Test-Taking Strategies': '✍️',
  'Note-Taking Skills': '📝',
  'Presentation Skills': '🎤',
  'Project Management': '📊',
  'Digital Skills': '💻',
  'Coding': '👨‍💻',
  'Robotics': '🤖',
  'Engineering': '⚙️',
  'Design Thinking': '🎨',
  'Innovation': '💡',
  'Entrepreneurship': '💼',
  'Financial Education': '💰',
  'Economics': '📈',
  'Civics': '⚖️',
  'Government': '🏛️',
  'World Cultures': '🌏',
  'World History': '📜',
  'American History': '🗽',
  'Earth Science': '🌎',
  'Life Science': '🧬',
  'Physical Science': '⚡',
  'Chemistry': '🧪',
  'Physics': '🔭',
  'Biology': '🦠',
  'Anatomy': '🧠',
  'Space Science': '🚀',
  'Weather': '☁️',
  'Climate': '🌡️',
  'Ecology': '🌳',
  'Geology': '🗻',
  'Astronomy': '🌠',
  'Marine Biology': '🐠',
  'Zoology': '🦁',
  'Botany': '🌺',
  'Genetics': '🧬',
  'Evolution': '🦕',
  'Microbiology': '🔬',
  'Nutrition': '🥗',
  'Health': '❤️',
  'Sports Science': '🏃',
  'Dance': '💃',
  'Theater': '🎭',
  'Film': '🎬',
  'Photography': '📷',
  'Digital Art': '🖼️',
  'Graphic Design': '🎨',
  'Web Design': '🌐',
  'Animation': '🎬',
  'Poetry': '📝',
  'Literature': '📚',
  'Grammar': '📖',
  'Vocabulary': '📚',
  'Reading Comprehension': '📖',
  'Writing Skills': '✍️',
  'Debate': '🗣️',
  'Media Studies': '📱',
  'Journalism': '📰',
  'Philosophy': '🤔',
  'Psychology': '🧠',
  'Sociology': '👥',
  'Anthropology': '🌏',
  'World Religions': '🕊️',
  'Ethics': '⚖️',
  'Logic': '🧩',
  'Critical Analysis': '🔍',
  'Research Methods': '📊',
  'Statistics': '📈',
  'Data Analysis': '📊',
  'Probability': '🎲',
  'Algebra': '➗',
  'Geometry': '📐',
  'Trigonometry': '📐',
  'Calculus': '📊',
  'Pre-Algebra': '➗',
  'Pre-Calculus': '📊',
  'Linear Algebra': '📐',
  'Number Theory': '🔢',
  'Discrete Mathematics': '🔢',
  'Applied Mathematics': '📊',
  'Mathematical Modeling': '📈',
  'Mathematical Logic': '🧩',
  'Mathematical Problem Solving': '🧮',
  'Mathematical Reasoning': '🤔',
  'Mathematical Communication': '💭',
  'Mathematical Connections': '🔗',
  'Mathematical Representation': '📊',
  'Mathematical Technology': '🖥️',
  'Mathematical Applications': '📱',
  'Mathematical History': '📜',
  'Mathematical Games': '🎲',
  'Mathematical Art': '🎨',
  'Mathematical Nature': '🌿',
  'Mathematical Music': '🎵',
  'Mathematical Sports': '⚽',
  'Mathematical Finance': '💰',
  'Mathematical Engineering': '⚙️',
  'Mathematical Science': '🔬',
  'Mathematical Computing': '💻'
}; 