// Theme-specific emoji decorations
export const themeDecorations: { [key: string]: string[] } = {
  Halloween: ['🎃', '👻', '🦇', '🕷️', '🕸️', '🧙‍♀️', '🌙', '🍬', '🧟‍♂️', '🏰'],
  Winter: ['❄️', '⛄', '🎄', '🎁', '☃️', '🧊', '🌨️', '🧣', '🧤', '🎿'],
  Spring: ['🌸', '🌺', '🦋', '🌱', '🌷', '🐝', '🌻', '🌼', '🐣', '🌈'],
  General: ['⭐', '🌟', '✨', '🎯', '📚', '🎨', '🔍', '💡', '🎓', '🌈']
};

// Subject emojis (removed duplicates)
export const themeEmojis: { [key: string]: string } = {
  General: '📚',
  Math: '🔢',
  Reading: '📖',
  Science: '🔬',
  History: '🏛️',
  Geography: '🌍',
  Art: '🎨',
  Music: '🎵',
  PhysicalEducation: '⚽',
  Technology: '💻',
  SocialStudies: '🌐',
  LanguageArts: '✍️',
  ForeignLanguage: '🗣️',
  SpecialEducation: '🌟',
  TestPrep: '📝',
  StudySkills: '📚',
  LifeSkills: '🌱',
  CareerEducation: '💼',
  CharacterEducation: '❤️',
  HealthEducation: '🏥',
  EnvironmentalScience: '🌿',
  ComputerScience: '🖥️',
  FinancialLiteracy: '💰',
  CriticalThinking: '🤔',
  CreativeWriting: '✏️',
  PublicSpeaking: '🎤',
  ResearchSkills: '🔍',
  ProblemSolving: '🧩',
  TimeManagement: '⏰',
  OrganizationSkills: '📊',
  LeadershipSkills: '👥',
  CommunicationSkills: '💭',
  TeamBuilding: '🤝',
  ConflictResolution: '🤲',
  DecisionMaking: '⚖️',
  GoalSetting: '🎯',
  StressManagement: '🧘',
  DigitalCitizenship: '🌐',
  MediaLiteracy: '📱',
  InformationLiteracy: '📰',
  CulturalAwareness: '🌏',
  GlobalEducation: '🗺️',
  EnvironmentalEducation: '🌳',
  CharacterDevelopment: '🌟',
  SocialSkills: '👥',
  EmotionalIntelligence: '❤️',
  GrowthMindset: '🌱',
  Mindfulness: '🧘',
  PositiveBehavior: '👍',
  SelfAwareness: '🤗',
  SelfManagement: '⚡',
  ResponsibleDecisionMaking: '🎯',
  RelationshipSkills: '🤝',
  SocialAwareness: '👀',
  CollegeReadiness: '🎓',
  CareerReadiness: '💼',
  NoteTakingSkills: '📝',
  PresentationSkills: '🎤',
  ProjectManagement: '📊',
  DigitalSkills: '💻',
  Coding: '👨‍💻',
  Robotics: '🤖',
  Engineering: '⚙️',
  DesignThinking: '🎨',
  Innovation: '💡',
  Entrepreneurship: '💼',
  FinancialEducation: '💰',
  Economics: '📈',
  Civics: '⚖️',
  Government: '🏛️',
  WorldCultures: '🌏',
  WorldHistory: '📜',
  AmericanHistory: '🗽',
  EarthScience: '🌎',
  LifeScience: '🧬',
  PhysicalScience: '⚡',
  Chemistry: '🧪',
  Physics: '🔭',
  Biology: '🦠',
  Anatomy: '🧠',
  SpaceScience: '🚀',
  Weather: '☁️',
  Climate: '🌡️',
  Ecology: '🌳',
  Geology: '🗻',
  Astronomy: '🌠',
  MarineBiology: '🐠',
  Zoology: '🦁',
  Botany: '🌺',
  Genetics: '🧬',
  Evolution: '🦕',
  Microbiology: '🔬',
  Nutrition: '🥗',
  Health: '❤️',
  SportsScience: '🏃',
  Dance: '💃',
  Theater: '🎭',
  Film: '🎬',
  Photography: '📷',
  DigitalArt: '🖼️',
  GraphicDesign: '🎨',
  WebDesign: '🌐',
  Animation: '🎬',
  Poetry: '📝',
  Literature: '📚',
  Grammar: '📖',
  Vocabulary: '📚',
  ReadingComprehension: '📖',
  WritingSkills: '✍️',
  Debate: '🗣️',
  MediaStudies: '📱',
  Journalism: '📰',
  Philosophy: '🤔',
  Psychology: '🧠',
  Sociology: '👥',
  Anthropology: '🌏',
  WorldReligions: '🕊️',
  Ethics: '⚖️',
  Logic: '🧩',
  CriticalAnalysis: '🔍',
  ResearchMethods: '📊',
  Statistics: '📈',
  DataAnalysis: '📊',
  Probability: '🎲',
  Algebra: '➗',
  Geometry: '📐',
  Trigonometry: '📐',
  Calculus: '📊',
  PreAlgebra: '➗',
  PreCalculus: '📊',
  LinearAlgebra: '📐',
  NumberTheory: '🔢',
  DiscreteMathematics: '🔢',
  AppliedMathematics: '📊',
  MathematicalModeling: '📈',
  MathematicalLogic: '🧩',
  MathematicalProblemSolving: '🧮',
  MathematicalReasoning: '🤔',
  MathematicalCommunication: '💭',
  MathematicalConnections: '🔗',
  MathematicalRepresentation: '📊',
  MathematicalTechnology: '🖥️',
  MathematicalApplications: '📱',
  MathematicalHistory: '📜',
  MathematicalGames: '🎲',
  MathematicalArt: '🎨',
  MathematicalNature: '🌿',
  MathematicalMusic: '🎵',
  MathematicalSports: '⚽',
  MathematicalFinance: '💰',
  MathematicalEngineering: '⚙️',
  MathematicalScience: '🔬',
  MathematicalComputing: '💻'
}; 