import {
  Body,
  Button,
  Container,
  Head,
  Hr,
  Html,
  Img,
  Preview,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';

interface WorksheetEmailTemplateProps {
  worksheetTitle: string;
  worksheetType: string;
  gradeLevel: string;
  subject: string;
  downloadUrl: string;
}

export const WorksheetEmailTemplate = ({
  worksheetTitle = "Sample Worksheet",
  worksheetType = "worksheet",
  gradeLevel = "Grade 5",
  subject = "Math",
  downloadUrl = "#"
}: WorksheetEmailTemplateProps) => (
  <Html>
    <Head />
    <Preview>
      Someone shared a {worksheetType} with you: {worksheetTitle}
    </Preview>
    <Body style={main}>
      <Container style={container}>
        {/* Header */}
        <Section style={header}>
          <Text style={logo}>🎓 VoiceVenture AI</Text>
          <Text style={tagline}>AI-Powered Educational Resources</Text>
        </Section>

        {/* Main Content */}
        <Section style={content}>
          <Text style={greeting}>Hello!</Text>
          
          <Text style={messageText}>
            Someone has shared an educational resource with you through VoiceVenture AI.
          </Text>

          {/* Worksheet Info Card */}
          <Section style={worksheetCard}>
            <Text style={worksheetTitleStyle}>{worksheetTitle}</Text>
            <Section style={worksheetMeta}>
              <Text style={metaItem}>
                <strong>Type:</strong> {worksheetType.charAt(0).toUpperCase() + worksheetType.slice(1)}
              </Text>
              <Text style={metaItem}>
                <strong>Subject:</strong> {subject}
              </Text>
              <Text style={metaItem}>
                <strong>Grade Level:</strong> {gradeLevel}
              </Text>
            </Section>
          </Section>

          {/* Download Button */}
          <Section style={buttonSection}>
            <Button style={button} href={downloadUrl}>
              Download Worksheet (PDF)
            </Button>
          </Section>

          <Text style={footerText}>
            This worksheet was created using AI technology to provide engaging and
            educational content tailored to the specified grade level and subject.
          </Text>
        </Section>

        <Hr style={hr} />

        {/* Footer */}
        <Section style={footer}>
          <Text style={footerText}>
            Generated by VoiceVenture AI - Transforming education through voice and AI
          </Text>
          <Text style={smallText}>
            This email was sent because someone shared an educational resource with you.
            If you didn't expect this email, you can safely ignore it.
          </Text>
        </Section>
      </Container>
    </Body>
  </Html>
);

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
};

const header = {
  padding: '20px 30px',
  backgroundColor: '#4f46e5',
  borderRadius: '8px 8px 0 0',
  textAlign: 'center' as const,
};

const logo = {
  color: '#ffffff',
  fontSize: '24px',
  fontWeight: 'bold',
  margin: '0 0 8px',
};

const tagline = {
  color: '#e0e7ff',
  fontSize: '14px',
  margin: '0',
};

const content = {
  padding: '30px',
};

const greeting = {
  fontSize: '18px',
  fontWeight: '600',
  color: '#374151',
  margin: '0 0 16px',
};

const messageText = {
  fontSize: '16px',
  lineHeight: '24px',
  color: '#6b7280',
  margin: '0 0 24px',
};

const worksheetCard = {
  backgroundColor: '#f9fafb',
  border: '1px solid #e5e7eb',
  borderRadius: '8px',
  padding: '20px',
  margin: '24px 0',
};

const worksheetTitleStyle = {
  fontSize: '20px',
  fontWeight: '700',
  color: '#111827',
  margin: '0 0 16px',
};

const worksheetMeta = {
  margin: '0',
};

const metaItem = {
  fontSize: '14px',
  color: '#6b7280',
  margin: '4px 0',
};

const buttonSection = {
  textAlign: 'center' as const,
  margin: '32px 0',
};

const button = {
  backgroundColor: '#4f46e5',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  lineHeight: '100%',
  padding: '12px 20px',
};

const hr = {
  borderColor: '#e5e7eb',
  margin: '20px 0',
};

const footer = {
  padding: '0 30px',
  textAlign: 'center' as const,
};

const footerText = {
  fontSize: '14px',
  color: '#6b7280',
  margin: '8px 0',
};

const smallText = {
  fontSize: '12px',
  color: '#9ca3af',
  margin: '8px 0',
};

export default WorksheetEmailTemplate; 